// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Webapi.ClientConsume;

#nullable disable

namespace Webapi.Migrations
{
    [DbContext(typeof(APIcontext))]
    [Migration("20240821174133_RenameNameToUsername")]
    partial class RenameNameToUsername
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Webapi.ClientConsume.ClientConsumeAPI", b =>
                {
                    b.Property<Guid>("Clordid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dir")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Px")
                        .HasColumnType("TEXT");

                    b.Property<int>("Qty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Clordid");

                    b.ToTable("ClientConsume");
                });
#pragma warning restore 612, 618
        }
    }
}
